language: bash
services: docker
addons:
  apt:
    packages:
    - qemu-user-static
before_install:
- sudo update-binfmts --enable qemu-aarch64
before_script:
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz.md5
- wget -nv http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz.sig
- md5sum -c ArchLinuxARM-aarch64-latest.tar.gz.md5
- gpg --recv-keys 68B3537F39A313B3E574D06777193F152BDBE6A6
- gpg --verify ArchLinuxARM-aarch64-latest.tar.gz.sig ArchLinuxARM-aarch64-latest.tar.gz
- wget -nv https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-3/qemu-aarch64-static
  -O qemu-aarch64-static
- chmod +x qemu-aarch64-static
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo service docker restart
script:
- docker build --squash -t mydatakeeper/cross-archlinux .
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push mydatakeeper/archlinux
  on:
    branch: master
env:
  global:
  - secure: IK4Dtg2MCcPxhyn5t/jbpAL4IarQkVilVsQN00YJP0B8Shw/A8DQwUA7MyhTaRgjlwW6UscLdj7h1ApTe1zk9li99PYdRoylK5s7wXP4SaTesF+hoz9L/Js01m4ON9kV3KymY4X5BtLwlZIjvwzSSUbI9mTmb8OgJ+ANi/FjDJL4ch5sgrnfw+9Z7JTjOrMM8+WlMGgVVzWJRtrG65B5IKzZfHiJmQObQoxAHfAHtgPyhfoCWXFx/QzEE7+bXY8gYZ4Dl8O1TkqCHP2M43HoRzQxDa8va59s1tza8oe0ZOsvP4dOXlX/w0QGJT4CQpRu7nT3uiUR+JYLcU+Vbdmeiv/lo7NMsj0LSH0PH6H8FqRogeUOppDagriRL5Wqk6NmJ3LDrMPIxdhCUIzYo8SIy9xuW6yUEhnVIrb1mprWneer8q8eGgtNY867DHdaCqfW08nU0W7ckq909Oj11/JJhGvsg9gUbvV2qIClrhYpF9iBIXoEp22KUU+7zJ3Zji5RFbLSg3FoSrePNEjKjszow26LPKEVcwo/Fqr1XZ1WMabYRPR6GAjRzgEW2hu+0/+KWU71cOR+HDvqmtiPjMjC80LXKUeggoY7nff7XNU3dCb4BCYCN9+pC6uymyLkkX+xsWQzEVJSX0NTHp85iHROm8fsjBbNDngliqiR0GpABmg=
  - secure: GP8Sq7FEXCLWe35/U6SvtmSgC7rthfMs53qM11m42ITfPz9fSYqiYhcpiMjJrD8AdWTuMsIpQrIolFwH/5FPY68SF43phMwQTpan7t2SofNEhFsC8Mg6Ok/gEPrNhvONGUutTdCw23qNIgLZ1A5LJ+eG0NkIredVwIChbTBgcXteW1DhA0aMViqRQUzw73DZdde6pe7sWlcgOFJ7nR/1Pca1VOIAVmOK0b+xLb2mKNKXJmnOogQHiuFIO8G5u8BG+0ZD5ZQLTwVmC1fg9MsyKLIIAOJE9Gg4yYCS9fvf8ikOVX2nENxwef0BqiNr40XRcdGD1eM45+gq/0oHXnVUK5TEYc7cqyCH3C1b5s28d3HPyAiabMnwkTKZphQVmHPpqs8lw3LDxL1zrB9bmZqWkMdUylLMzy5hntWpDIDIJiS2KpQGht5y/HCDWl1aLGn19fPuXraPBwVgNVr3DdMK6Q9AuGDExSvP+38C33Tj13HE+SCH9Gy/hKzTKyFgp4VoZZBxgiu3M3l+bqwu/cJOtQS3+qFGg1YDd5IJrxQ/5aiARH8tvkmHqECsxkBlrvIfKmgsLY2cSL4PTHod/3p303IeY7Z5U06E2MHRnLla7G83B8PNb5kFLa0tiDxBgmC8zYq+DFTwq8qyzZBE9rGY1T6WNPrqQNXsVLGw72RKGJw=
