language: bash
services: docker
addons:
  apt:
    packages:
    - qemu-user-static
before_install:
- sudo update-binfmts --enable qemu-aarch64
before_script:
- wget -nv https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-3/qemu-aarch64-static
  -O qemu-aarch64-static
- chmod +x qemu-aarch64-static
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo service docker restart
script:
- docker build --squash -t mydatakeeper/aarch64-archlinux .
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push mydatakeeper/aarch64-archlinux
  on:
    branch: master
env:
  global:
  - secure: r0fogicxZA1+xEIWm+i+/+ZXo84edjH3Eqj8WT1SjV0d2l5r0UYiZbNr7/5OXDW/rl/TXQvUqtcM8+rbHWzAt1h7oozyj1hXWIlyb9y6kCk7Tac/4n2uQV78JwuvrY2jJ9Es+HAc7innSDZBiv/kOTgQhkcOXImpxkZjTGix+GBA40W+iMdGuIDo9SINPOUDkbRG1OpRruJWs4tX4gGK/goRy8+4MbV8tscTdSQedn6lmav/6zgfsAYeAdqzeygZcLwwmroGS5ruwc4iS60T9AwJyvN9oNCJQg5Md0tnYqKf10BWaPyfgKAx5TrkYsuUF/1q8ko8m3eJRD25mhZWqNAKcR80wTsjG3tw6+aNy638MyQnTP4KWZ/mxa5HHOFc6nnHq/absMcbDO1QEk/09D2L/LjRiWejl6KeO0d138gOFJdRhIgo/p/8qY0ma4hNXzwzZkcnXHgVtDwi3McTFNKTVUWkzuqEVYkmo8Y+zy/DXMaxODgM+a6xOkcDzfJ8kwaBkip703jPODYiiTpQdXwWiO407K10S4Nm7wX6JjNWGZ1pyLLsqPzQf0b3RQDdOGBQY9XpFTA8yzphG4vlCvoay6rwpjQI1/rf+Fv/Vwvnx28mX3DSoO2kwv4GBbQxOGI79/cT00qt8zB+MkOq3m1xSH1Pq+hNfDPquvXS5x8=
  - secure: m+lrBh6jP3W8dqgZA8Xyh4sc6ujXMQ5lOoMJmtcPAXpf6vRuTxq1z+LXK5rNUzImYwaA2ZsOKbRrM5QQw+aTUbd4zivlyCkPuRGZ5Nmk7W8eps3XIg6f2ybp4vG/UMS9M8ICgZXWkfHVICHdGLYTqccI43pQpoFGgqqWEee13EXke+gDQb7FZAK2lWHoWKNYMxjBinUKh6FujS1ofUqGY5kIBYc+8RyCmaCmok1gfTNVT/gX5aBNv2Dw142jIuCoEDJYQgltGdARL91RlvdtZUSdW2eNoEgaVrwpejJbu3gYL/JqyOgC9spKjblmfRz+yT/eUt6PhlKQdWQgNgnu9XtCEZRFZm/Mmo4CD2kuNNADuK/v+3pAaWRR0CDIcz9xrmCNMCdJyvv7MdlLl1NDfTuTvyX08aMCOEExz8B4ES16jR1wMKSy1AaPUfDk/WiMPbqORLrZGGxiHHsmA1m8FP+GaNP8l+c1G9hYXj61vI9y1XOobJrzkI6BeM2yzeBsMQN3cyC/NSjD9n6mbhfTzuT5qSAQq/puuysVH4Q1bCbSgkEvm866AlMlenExqwaUxvSekvxhNHU7w12N2WdyHsuxCr6RsplT4z8ocWOnoimdiAy9WWvCLj4uYGmY7d8L8f+YQlHKqkf+7whVjjk8lseGy49VvFeSdyDNTAEP7ik=
